### ISSUE TITLE
All Ledger transactions display "An error happened!!!" info:

### ISSUE THREAD

**Issue by pawelvod** [crypto-com/chain-desktop-wallet#1260] opened 2022-10-12 13:23 UTC
DEFI DESKTOP WALLET v1.3.2
Crypto.org Ledger v2.16.7
Windows 10. 

I cant't sign any transaction with ledger i.e. "withdraw reward". After clicking "confirm" window "An error happened!!!" appears.
Description in the window:
"Query failed with (18)
- decoding bech32 failed
- string not all lowercase or all uppercase
- invalid request
"

**Comment by knutab** [comment] 2022-10-16 12:55
I am having the same issue. Cant Restake or Claim Rewards
![error-restaking](https://user-images.githubusercontent.com/7900499/196036580-55ca5f1e-ba5e-4d1b-80c7-09e042362a19.PNG)

**Comment by crypto-matto** [comment] 2022-10-17 08:11
Hi @knutab, I've studied the issue & couldn't reproduce it on my side. May I know which Ledger device do you have, and is the device's firmware updated to latest version on [Ledger Live](https://www.ledger.com/ledger-live)? Thanks.

Most importantly, please make sure you got your Ledger address’s:
- mnemonic seed
- “Index”
- “Standard”
You could locate “Index” & “Standard” at our Wallet List page. You'll always able to import your Ledger address again as long as you got all these right.

**Comment by knutab** [comment] 2022-10-17 08:31
Hi, I am using Ledger Nano X with Ledger Live updated to the latest version
2.48.0
I do have my mnemonic seed, but how can I see the Index and Standard?

**Comment by crypto-matto** [comment] 2022-10-17 08:43
> Hi, I am using Ledger Nano X with Ledger Live updated to the latest version 2.48.0 I do have my mnemonic seed, but how can I see the Index and Standard?

You may check your firmware in Ledger Live under: 
- "My Ledger" -> "Firmware"
<img width="1005" alt="螢幕截圖 2022-10-17 下午4 33 16" src="https://user-images.githubusercontent.com/74586409/196130414-06c28287-98bf-43e3-bd32-14e87f806376.png">

For “Index” & “Standard”:
- Button at Bottom-Left navbar menu -> "Wallet List" -> “Index” & “Standard”
<img width="1262" alt="螢幕截圖 2022-10-17 下午4 34 27" src="https://user-images.githubusercontent.com/74586409/196131246-81b98ba2-b4ea-4988-b77f-b4cf45b0a6d2.png">

**Comment by knutab** [comment] 2022-10-17 08:51
Thanks.

[image: image.png]

Firmware is up to date.

**Comment by pawelvod** [comment] 2022-10-17 08:59
Nano S. All latest firmware in my case but... Yesterday i signed all transaction. Claim, restake and stake during this time (error apear) nothing updated.

**Comment by crypto-matto** [comment] 2022-10-17 09:29
> Nano S in my case. All latest firmware but... Yesterday I signed all transaction: claim, restake and stake. Before this nothing updated.

Hi @pawelvod, do you mean you're able to perform all `claim, restake and stake` transactions now? Or it's still not working? What about other type of transactions like Asset Transfer, NFT-related transactions?

**Comment by pawelvod** [comment] 2022-10-17 09:42
Yes. All works ok now. Transfers too. I have no nfts so i can't confirm that.

**Comment by knutab** [comment] 2022-10-17 10:54
I just tried to restake again, and now it worked!

**Comment by crypto-matto** [comment] 2022-10-18 05:58
Hi @knutab @pawelvod,

Just found that this issue can be reproduced when a user:
1. Make a Cronos Chain Transfer Transaction
2. After that making a Crypto.org Chain Staking Transaction

And the workaround for the moment to solve this is to:
1. Switch to any other wallet address
2. Switch back to the Ledger wallet address

I'll be handling this issue in the following fix patch. Thanks for your reports!

**Comment by elias7905** [comment] 2022-10-18 07:35
![image](https://user-images.githubusercontent.com/101262042/196366101-110688d4-1426-426c-ae24-0fd06107ea53.png)
I'm still having this issue: 3.35pm tuesday 18th October 2022 Epoch: 1666078520

**Comment by crypto-matto** [comment] 2022-10-24 07:42
Hi @knutab @pawelvod @elias7905, this issue is fixed in the latest 1.3.3 release. Feel free to update the wallet app. Thanks!

**Closed by crypto-matto** 2022-10-24 07:42 UTC
