### ISSUE TITLE
Problem: Ledger does not accept custom derivation path

### ISSUE THREAD

**Issue by calvinaco** [crypto-com/chain-desktop-wallet#309] opened 2021-03-24 02:31 UTC
If one use the Devnet with custom derivation path, the address derived is still the default derivation path.

**Comment by leejw51crypto** [comment] 2021-03-24 03:22
started

**Comment by leejw51crypto** [comment] 2021-03-24 03:31
full path config is not allowed with the ledger,
because, it should be bip44 , 394 , to interact  with cro inside the ledger

it will be adding "index" in creating ledger wallet

**Comment by linfeng-crypto** [comment] 2021-03-24 03:47
yes, 394 is hard coded in ledger app

**Comment by Nawaz-Malik143** [comment] 2021-03-24 05:39
#304

**Comment by Nawaz-Malik143** [comment] 2021-03-24 05:39
#303

**Comment by Nawaz-Malik143** [comment] 2021-03-24 05:39
#307

**Comment by Nawaz-Malik143** [comment] 2021-03-24 05:40
#308

**Comment by Nawaz-Malik143** [comment] 2021-03-24 07:12
#310

**Comment by Nawaz-Malik143** [comment] 2021-03-24 07:13
#310

**Comment by Nawaz-Malik143** [comment] 2021-03-24 07:13
#310

**Comment by Nawaz-Malik143** [comment] 2021-03-24 07:13
Duplicate of #

**Closed** 2021-03-24 14:28 UTC
