### ISSUE TITLE
Problem: Withdrawal rewards to include in Home Page

### ISSUE THREAD

**Issue by crypto-matto** [crypto-com/chain-desktop-wallet#268] opened 2021-02-23 04:14 UTC
Feedback from internal QA:
https://docs.google.com/document/d/1aM1SM9oa67P3MEU6hhppnWgJq9TbLxlDzIAf6DRErBU/edit#

**Comment by eddycpc** [comment] 2021-02-23 06:35
Duplicate of https://github.com/crypto-com/chain-desktop-wallet/issues/257

**Closed by eddycpc** 2021-02-23 06:35 UTC
