### ISSUE TITLE
Problem: Missing a notification section

### ISSUE THREAD

**Issue by crypto-matto** [crypto-com/chain-desktop-wallet#724] opened 2021-10-05 07:43 UTC
**Is your feature request related to a problem? Please describe.**
Currently we're missing of any notification mechanisms for making announcement / pushing promotion messages. 

**Describe the solution you'd like**
- A `Notification` / `News` Tab on the navbar
- Design similar to `Governance` Page
- Have to log & illustrate whether a news is read or not
- We may also display latest news within 1 week in a prompt popup when a user first open the app & the news has never been read
- An external self-hosted notification endpoint is also required

**Comment by XinyuCRO** [comment] 2022-06-27 02:10
Duplicate of #1145

**Closed by XinyuCRO** 2022-06-27 02:10 UTC
Labels: enhancement, UI, discussion needed
